about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

api/urls.py
from django.urls import include, path

from api.views import (
    FavoriteRecipeViewSet,
    IngredientListView,
    PurchaseViewSet,
    SubscribeViewSet
)
from rest_framework.routers import DefaultRouter

router_v1 = DefaultRouter()

router_v1.register('ingredients', IngredientListView)
router_v1.register('subscriptions', SubscribeViewSet)
router_v1.register('favorites', FavoriteRecipeViewSet)
router_v1.register('purchases', PurchaseViewSet)

urlpatterns = [
    path('v1/', include(router_v1.urls)),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('recipes.urls')),
]

handler404 = "users.views.page_not_found"  # noqa
handler500 = "users.views.server_error"  # noqa


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

templates/authForm.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Войти на сайт{% endblock title %}
{% block static %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block nav %}
    {% include "nav.html" %}
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Войти на сайт</h1>
    </div>
    <div class="form-container">
        <form class="form">
            <div class="form__group">
                <label for="id_username" class="form__label">Имя</label>
                <div class="form__field-group">
                    <input type="text" name="username" id="id_username" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_password" class="form__label">Пароль</label>
                <div class="form__field-group">
                    <input type="password" name="password" id="id_password" class="form__input">
                    <span class="form__error">Имя пользователя и пароль не совпадают. Введите правильные данные.</span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Войти</button>
                <a class="form__forgot-link">Забыли пароль?</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/authorRecipe.html
{% extends "base.html" %}
{% load recipe_filters %}
{% load static %}
{% block title %}Рецепты{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock static %}

{% block nav %}
    {% include "nav.html" %}
{% endblock %}


{% block content %}
    <div class="main__header">
        <h1 class="main__title">{{ author.get_full_name }}</h1>

        {% include "tags.html" %}

    </div>
    {% if user != author %}
        {% if user.is_authenticated %}
        <div class="author-subscribe" data-author="{{ author.id }}">
        {% if user|is_subscribe:author %}
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться от автора</button></p>
        {% else %}
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
        {% endif %}
        {% endif %}
        </div>
    {% endif %}
    <div class="card-list" >
        {% load thumbnail %}
        {% for recipe in page %}
        {% thumbnail recipe.image "900x500" crop="center" as im %}
        <div class="card" data-id="{{ recipe.id }}">
            <a href="{% url 'recipe_view' recipe.id %}" class="link" target="_blank"><img src="{{ im.url }}" alt="Картинка" class="card__image"></a>
        {% endthumbnail %}
            <div class="card__body">
                <a class="card__title link" href="{% url 'recipe_view' recipe.id %}" target="_blank">{{recipe.name}}</a>
                <ul class="card__items">
                    {% for tag in recipe.tag.all %}
                        <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.title }}</span></li>
                    {% endfor %}
                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span> {{recipe.cooking_time}} мин.</p>
                    <p class="card__text"><span class="icon-user"></span> {{recipe.author}}</p>
                </div>
            </div>
            {% if user.is_authenticated %}
            <div class="card__footer">
                {% include 'buttons.html' %}
            </div>
            {% endif %}
        </div>
        {% endfor %}

</div>

    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}

{% endblock content %}

{% block script %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'authorRecipe.js' %}"></script>
{% endblock script %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}{% endblock %}</title>

    {% block static %}{% endblock %}
</head>
<body class="body">

{% csrf_token %}

{% block nav %}{% endblock %}

<main class="main container">
    {% block content %}{% endblock content %}
</main>

{% include "footer.html" %}

{% block script %}{% endblock script %}
</body>
</html>

templates/buttons.html
{% load recipe_filters %}

{% if recipe|in_shoplist:user %}
    <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
{% else %}
    <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
{% endif %}
{% if recipe|is_favorite:user %}
    <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
{% else %}
    <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
{% endif %}

templates/footer.html
<footer class="footer">
        <div class="footer__container container">
            <a href="https://github.com/Fr33vvay/foodgram-project" class="footer__brand link">Продуктовый помощник</a>
            <ul class="footer__items">
                <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
                <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
            </ul>
        </div>
</footer>

templates/formChangeRecipe.html
{% extends 'base.html' %}
{% load recipe_filters %}
{% load static %}

{% block title %}Редактирование рецепта{% endblock title %}

{% block static %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock static%}

{% block nav %}
    {% include "nav.html" %}
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Редактирование рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
            <label for="{{ form.name.id_for_label }}" class="form__label">Название рецепта</label>
            <div class="form__field-group">
                {{ form.name|addclass:"form__input" }}
                {% if form.name.errors %}
                    {% for error in form.name.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag_choice, tag_value in form.tag.field.choices %}
                            <div class="tags__item">
                                <input
                                    type="checkbox"
                                    name="tag"
                                    value="{{ tag_choice.instance.pk }}"
                                    id="id_{{ tag_choice.instance.value }}"
                                    class="tags__checkbox tags__checkbox_style_{{ tag_choice.instance.color }}">
                                    <label for="id_{{ tag_choice.instance.value }}" class="tags__label">{{ tag_choice.instance.title }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    {% if form.errors %}
                        {% for error in form.tag.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                    {% if ingredients %}
                        {% for ing in ingredients %}
                        <div class="form__field-item-ingredient" id="ing_{{ ing.ingredients.id }}">
                            <span> {{ ing.ingredient.title }} {{ ing.quantity }} {{ ing.ingredient.dimension }}</span>
                            <span class="form__field-item-delete"></span>
                            <input id="nameIngredient_{{ ing.ingredient.id }}" name="nameIngredient_{{ ing.ingredient.id }}" type="hidden" value="{{ ing.ingredient.title }}">
                            <input id="valueIngredient_{{ ing.ingredient.id }}" name="valueIngredient_{{ ing.ingredient.id }}" type="hidden" value="{{ ing.quantity }}">
                            <input id="unitsIngredient_{{ ing.ingredient.id }}" name="unitsIngredient_{{ ing.ingredient.id }}" type="hidden" value="{{ ing.ingredient.dimension }}">
                        </div>
                        {% endfor %}
                    {% endif %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error">
                        {% if form.non_field_errors %}
                            <div class="non-field-errors">
                                {% for error in form.non_field_errors %}
                                <p class="form-error">{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </span>
                </div>
            </div>
            <div class="form__group">
            <label for="{{ form.cooking_time.id_for_label }}" class="form__label">Время приготовления</label>
            <div class="form__field-group form__field-group_time">
                {{ form.cooking_time|addclass:"form__input" }}
                <label for="id_time" class="form__label">минут</label>
                {% if form.cooking_time.errors %}
                    {% for error in form.cooking_time.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
            <div class="form__group">
            <label for="{{ form.description.id_for_label }}" class="form__label">Описание</label>
            <div class="form__field-group">
                {{ form.description|addclass:"form__textarea" }}
                {% if form.description.errors %}
                    {% for error in form.description.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
            <div class="form__group">
            <span class="form__label">Загрузить фото</span>
            <div class="form__field-group">
                {{ form.image|addclass:"file" }}
                {% if form.image.errors %}
                    {% for error in form.image.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
            <div class="form__footer">
                <button class="button button_style_blue">Сохранить</button>
                <a style="margin-left: 2.5em" href="{% url 'recipe_delete' recipe.id %}" class="form__ingredient-link">Удалить</a>
            </div>
        </form>
    </div>
{% endblock content %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
{% endblock script %}

templates/index.html
{% extends 'base.html' %}
{% load recipe_filters %}
{% load static %}

{% block title %}Рецепты{% endblock title %}

{% block static %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock static %}

{% block nav %}
    {% include "nav.html" with index=True %}
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Рецепты</h1>

        {% include "tags.html" %}

    </div>
    <div class="card-list">
        {% load thumbnail %}
        {% for recipe in page %}
        {% thumbnail recipe.image "900x500" crop="center" as im %}
        <div class="card" data-id="{{ recipe.id }}">
            <a href="{% url 'recipe_view' recipe.id %}" class="link" target="_blank"><img src="{{ im.url }}" alt="Картинка" class="card__image"></a>
        {% endthumbnail %}
            <div class="card__body">
                <a class="card__title link" href="{% url 'recipe_view' recipe.id %}" target="_blank">{{recipe.name}}</a>
                <ul class="card__items">
                    {% for tag in recipe.tag.all %}
                        <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.title }}</span></li>
                    {% endfor %}
                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span> {{recipe.cooking_time}} мин.</p>
                    <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' recipe.author %}" style="color: black">{{recipe.author}}</a></p>
                </div>
            </div>
            {% if user.is_authenticated %}
                <div class="card__footer">
                    {% include 'buttons.html' %}
                </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>

    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}

{% endblock content %}

{% block script %}
    {% if user.is_authenticated %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'indexAuth.js' %}"></script>
    {% else %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'indexNotAuth.js' %}"></script>
    {% endif %}
{% endblock script %}

templates/myFollow.html
{% extends "base.html" %}
{% load recipe_filters %}
{% load static %}

{% block title %}Мои подписки{% endblock title %}

{% block static %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css'%}">
{% endblock static %}

{% block nav %}
    {% include "nav.html" with subscriptions=True %}
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    <div class="card-list">
    {% for subscription in subscriptions %}
        <div class="card-user" data-author={{ subscription.author.id }}>
        <div class="card-user__header">
            <h2 class="card-user__title">{{ subscription.author.get_full_name }}</h2>
        </div>
        <div class="card-user__body">
            {% load thumbnail %}
            {% for recipe in subscription.author.recipes.all|slice:":3" %}
            <ul class="card-user__items">
                <li class="card-user__item">
                    <div class="recipe">
                        {% thumbnail recipe.image "100x100" crop="center" as im %}
                        <img src="{{ im.url }}" alt="Картинка" class="recipe__image">
                        {% endthumbnail %}
                        <h3 class="recipe__title"><a href="{% url 'recipe_view' recipe.id %}" class="link" target="_blank">{{ recipe.name }}</a></h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                    </div>
                </li>
            {% endfor %}
            {% if subscription.author.recipes.all.count > 3 %}
                <li class="card-user__item">
                    <a href="{% url 'profile' subscription.author %}" class="card-user__link link">Еще {{ subscription.author.recipes.all.count|add:-3 }}
                        {% declension subscription.author.recipes.all.count|add:-3 'рецепт' %}</a>
                </li>
            {% endif %}
            </ul>
        </div>
        <div class="card-user__footer">
            <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
        </div>
        </div>
    {% endfor %}
    </div>

    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
{% endblock content %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'myFollow.js' %}"></script>
{% endblock script %}

templates/nav.html
{% load recipe_filters %}
<header class="header">
      <nav class="nav">
          <div class="nav__container container">
              {% if user.is_authenticated %}
              <ul class="nav__items list">
                  <li class="nav__item {% if index %} nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                  <li class="nav__item {% if subscriptions %} nav__item_active {% endif %}"><a href="{% url 'subscribe' %}" class="nav__link link">Мои подписки</a></li>
                  <li class="nav__item {% if new_recipe %} nav__item_active {% endif %}"><a href="{% url 'new_recipe' %}" class="nav__link link">Создать рецепт</a></li>
                  <li class="nav__item {% if favorites %} nav__item_active {% endif %}"><a href="{% url 'favorites' %}" class="nav__link link">Избранное</a></li>
                  <li class="nav__item {% if purchases %} nav__item_active {% endif %}"><a href="{% url 'purchases' %}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{% purchase_count user %}</span></li>
              </ul>

              <ul class="nav__items list">
                  <li class="nav__item{% if password_change %} nav__item_active{% endif %}"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                  <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход: {{ user.username }}</a></li>
              </ul>
              {% else %}
              <ul class="nav__items list">
                <li class="nav__item nav__item_active"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
{#                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Список покупок <span class="badge badge_style_blue nav__badge" id="counter">4</span></a></li>#}
              </ul>

              <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
              </ul>
              {% endif %}
          </div>
      </nav>
  </header>

templates/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if items.has_previous %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.previous_page_number }}{{ filters }}"><span class="icon-left"></span></a></li>
        {% else %}
            <li class="pagination__item"><a class="pagination__link link" href="#"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if items.number == i %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link">{{ i }}</a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}{{ filters }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if items.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.next_page_number }}{{ filters }}"><span class="icon-right"></span></a></li>
        {% else %}
            <li class="pagination__item"><a class="pagination__link link" href="#"><span class="icon-right"></span></a></li>
        {% endif %}
    </ul>
</nav>

templates/reg.html
{% extends 'base.html' %}
{% load recipe_filters %}
{% load static %}
{% block title %}Регистрация{% endblock title %}
{% block static %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock static %}

{% block nav %}
    {% include "nav.html" %}
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Регистрация</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" action="{% url 'signup' %}">
                {% csrf_token %}
                    {% for field in form %}
                    <div class="form__group">
                        <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
                            <div class="form__field-group">
                                {{ field|addclass:"form__input" }}
                                {% if form.errors %}
                                    {% for error in field.errors %}
                                        <span class="form__error">{{ error|escape }}</span>
                                    {% endfor %}
                                 {% endif %}
                            </div>
                    </div>
                    {% endfor %}
            <div class="form__footer">
                <button class="button button_style_blue">Вперёд!</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/shopList.html
{% extends "base.html" %}
{% load static %}

{% block title %}Список покупок{% endblock title %}

{% block static %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css'%}">
{% endblock static %}

{% block nav %}
    {% include "nav.html" with purchases=True %}
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list card-list_column">
        {% load thumbnail %}
        <ul class="shopping-list">
            {% for recipe in recipes %}
                <li class="shopping-list__item" data-id="{{ recipe.id }}">
                    <div class="recipe recipe_reverse">
                        {% thumbnail recipe.image "100x100" crop="center" as im %}
                        <img src="{{ im.url }}" alt="Картинка" class="recipe__image recipe__image_big">
                        {% endthumbnail %}
                        <h3 class="recipe__title"><a href="{% url 'recipe_view' recipe.id %}" class="link" target="_blank">{{ recipe.name }}</a></h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                    </div>
                    <a  class="shopping-list__button link" href="{% url 'delete_purchase' recipe.id %}">Удалить</a>
                </li>
            {% endfor %}
        </ul>

        <a href="{% url 'download' %}"><button class="button button_style_blue">Скачать список</button></a>
    </div>
{% endblock content %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'shopList.js' %}"></script>
{% endblock script %}

templates/tags.html
{% load recipe_filters %}

<ul class="tags">
    {% with  filter_value=request.GET|get_tag_filter %}
        {% for tag in tags %}
            <li class="tags__item">
                <a id="{{ tag.title }}"
                   class="tags__checkbox tags__checkbox_style_{{ tag.color }}
                    {% if tag.title in filter_value %} tags__checkbox_active {% endif %}"
                   href="?{{ request|get_filter_link:tag }}"></a>
                <span class="tags__label">{{ tag.title }}</span>
            </li>
        {% endfor %}
    {% endwith %}
</ul>